name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: install
      run: |
        go install ./cmd/neva
        echo "$GOPATH/bin" >> $GITHUB_PATH
    - name: test
      # IMPORTANT: "-p 1" is a temporary fix for https://github.com/nevalang/neva/issues/767
      # It set's number of packages that can be run in parallel to one (sequentially)
      run: go test -v -count=1 -p 1 ./...
